# Generated by Django 3.0.2 on 2020-03-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(default='', max_length=254)),
                ('subject', models.CharField(max_length=254)),
                ('message', models.CharField(max_length=1000)),
                ('date_sent', models.DateTimeField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(default='None', max_length=254)),
                ('date_created', models.DateTimeField(editable=False)),
                ('extra_amount', models.FloatField(default=0.0)),
                ('end_date', models.DateTimeField(editable=False)),
                ('remaining_amount', models.FloatField(default=0.0)),
                ('eligibility', models.CharField(default='', max_length=400)),
                ('notified', models.BooleanField(default=False)),
                ('current_order_id', models.CharField(default='', max_length=254)),
                ('regular_count', models.IntegerField(default=0)),
                ('other_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_subscribed', models.DateTimeField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'Subscribers',
            },
        ),
    ]
