# Generated by Django 3.0.2 on 2020-03-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='No Date Provided', max_length=24)),
                ('time', models.CharField(default='No Time Provided', max_length=24)),
                ('on_going', models.BooleanField(default=True)),
                ('type_op', models.CharField(default='', max_length=50)),
                ('completed_status', models.CharField(default='', max_length=500)),
                ('completion_date', models.DateTimeField(editable=False)),
                ('created_date', models.DateTimeField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'Tracker Details',
            },
        ),
    ]
