# Generated by Django 3.0.2 on 2020-03-09 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(blank=True, max_length=254)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('address', models.CharField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=8)),
                ('subscription_plan', models.CharField(default='off', max_length=4)),
                ('news_letter_subscription', models.CharField(default='off', max_length=4)),
                ('profile_image', models.CharField(default='No', max_length=254)),
                ('qr_code_data', models.BinaryField()),
                ('contract_name', models.ForeignKey(default='Geethanjali College of Engineering and Technology', on_delete=django.db.models.deletion.CASCADE, to='contracts.Contracts')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Removed_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_removed', models.DateTimeField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'Removed Users',
            },
        ),
        migrations.CreateModel(
            name='Password_Reset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_id', models.CharField(default='', max_length=200)),
                ('date_sent', models.DateTimeField(editable=False)),
                ('email', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Password Resets',
            },
        ),
        migrations.CreateModel(
            name='OneSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default='', max_length=254)),
                ('enabled', models.BooleanField(default=True)),
                ('type_os', models.CharField(default='', max_length=254)),
                ('date_created', models.DateTimeField(editable=False)),
                ('email', models.ForeignKey(default='wasche.services@gmail.com', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Onesignal Data',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_msg', models.CharField(default='notify', max_length=254)),
                ('sent_from', models.CharField(default='', max_length=254)),
                ('title', models.CharField(default='', max_length=254)),
                ('msg', models.CharField(default='', max_length=1000)),
                ('seen', models.BooleanField(default=False)),
                ('image_url', models.CharField(default='No', max_length=254)),
                ('date_created', models.DateTimeField(editable=False)),
                ('email', models.ForeignKey(default='wasche.services@gmail.com', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
