# Generated by Django 2.2 on 2020-03-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onesignal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
